const fs = require('fs');
const dictPath = 'app/i18n/dictionaries/vi.json';
const dict = JSON.parse(fs.readFileSync(dictPath, 'utf8'));
const newKeys = {
    "selectSupplier": "-- Chọn nhà cung cấp --",
    "selectWarehousePlaceholder": "-- Chọn kho hàng --",
    "customProductOption": "+ Nhập sản phẩm ngoài",
    "pleaseSelectProduct": "Vui lòng chọn sản phẩm.",
    "pleaseEnterCustomName": "Vui lòng nhập tên sản phẩm ngoài.",
    "qtyMustBeGreaterThanZero": "Số lượng phải lớn hơn 0.",
    "deleteConfirm": "Bạn có chắc chắn muốn xóa hóa đơn {{code}} không?",
    "deleteFailed": "Xóa hóa đơn thất bại",
    "cancelConfirm": "Bạn có chắc chắn muốn hủy hóa đơn {{code}} không?",
    "cancelFailed": "Hủy hóa đơn thất bại",
    "pleaseSelectSupplier": "Vui lòng chọn nhà cung cấp.",
    "pleaseAddItems": "Vui lòng thêm ít nhất một mặt hàng.",
    "pleaseEnterProductName": "Vui lòng nhập tên sản phẩm ở dòng thứ {{line}}.",
    "createFailed": "Lỗi khi tạo hóa đơn",
    "pleaseSelectWarehouse": "Vui lòng chọn kho hàng để duyệt.",
    "approveSuccess": "Duyệt hóa đơn thành công",
    "approveFailed": "Duyệt hóa đơn thất bại",
    "statusDraft": "Nháp",
    "statusApproved": "Đã duyệt",
    "statusPartial": "Thanh toán 1 phần",
    "statusPaid": "Đã thanh toán",
    "statusCancelled": "Đã hủy",
    "title": "Hóa Đơn Mua Hàng",
    "description": "Quản lý danh sách các hóa đơn mua hàng từ nhà cung cấp.",
    "createBill": "Tạo Hóa Đơn Mới",
    "all": "Tất Cả",
    "bills": "Hóa đơn",
    "draft": "Đang Xử Lý",
    "pendingApproval": "Chờ duyệt",
    "approvedDebt": "Công Nợ",
    "partialPaid": "Thanh Toán 1 Phần",
    "debt": "Còn nợ",
    "paid": "Hoàn Tất",
    "completed": "Đã thanh toán",
    "searchPlaceholder": "Tìm kiếm theo mã, nhà cung cấp, hoặc trạng thái...",
    "colSystemCode": "Mã Hệ Thống",
    "colSupplierInvoice": "Nhà Cung Cấp / Số HĐ",
    "colDateSupplier": "Ngày Hóa Đơn",
    "colTags": "Thẻ",
    "colDueDate": "Hạn Kế Toán",
    "colTotal": "Tổng Tiền",
    "colPaid": "Đã Thanh Toán",
    "colStatus": "Trạng Thái",
    "colActions": "Thao Tác",
    "noBillsFound": "Không tìm thấy hóa đơn nhập hàng nào.",
    "viewTooltip": "Xem chi tiết",
    "editTooltip": "Chỉnh sửa",
    "approveTooltip": "Duyệt hóa đơn",
    "approveBtn": "Duyệt",
    "deleteTooltip": "Xóa",
    "cancelBillTooltip": "Hủy hóa đơn",
    "approveModalTitle": "Duyệt Hóa Đơn Nhập",
    "approveModalWarning1": "Hóa đơn này sẽ được chuyển trạng thái thành Đã Duyệt và được ghi nhận vào Công Nợ nhà cung cấp.",
    "approveModalWarning2": "Hệ thống sẽ tự động tạo phiếu nhập kho tương ứng cho các mặt hàng trong hóa đơn này.",
    "approveModalWarning3": "Bạn sẽ không thể thay đổi thông tin mặt hàng sau khi duyệt.",
    "selectWarehouse": "Chọn Kho Hàng",
    "cancelModalBtn": "Hủy bỏ",
    "approvingBtn": "Đang duyệt...",
    "approveModalBtn": "Xác nhận duyệt",
    "editTitle": "Sửa Hóa Đơn Nhập",
    "addTitle": "Tạo Hóa Đơn Mới",
    "supplierLabel": "Nhà Cung Cấp *",
    "orderLabel": "Đơn Đặt Hàng (Tùy chọn)",
    "selectOrder": "-- Chọn theo ĐĐH --",
    "dateLabel": "Ngày Hóa Đơn *",
    "dueDateLabel": "Hạn Thanh Toán",
    "supplierInvoiceLabel": "Số HĐ (Tùy chọn)",
    "notesLabel": "Ghi chú",
    "tagsLabel": "Thẻ Quản Lý",
    "attachments": "Tài liệu đính kèm",
    "deleteFileTooltip": "Xóa tài liệu này",
    "uploadError": "Tải thất bại",
    "uploadingBtn": "Đang tải...",
    "addDocumentBtn": "Thêm tài liệu",
    "itemsTitle": "Danh Sách Sản Phẩm / Chi Phí",
    "selectFromInventory": "Chọn từ kho",
    "customEntry": "Nhập tay",
    "productNameLabel": "Tên Sản Phẩm",
    "selectProductPlaceholder": "Chọn sản phẩm...",
    "customNamePlaceholder": "Nhập tên hàng hóa / dịch vụ...",
    "unitLabel": "ĐVT",
    "unitPlaceholder": "ĐVT",
    "unitPriceLabel": "Đơn giá",
    "taxLabel": "Thuế %",
    "qtyLabel": "SL",
    "addItemBtn": "Thêm dòng",
    "itemNotesLabel": "Ghi chú mặt hàng",
    "printedOnTransfer": "(In trên Phiếu Nhập Kho)",
    "useInventoryDesc": "Lấy mô tả từ kho",
    "customDesc": "Tự nhập",
    "itemNotesPlaceholder": "Nhập ghi chú...",
    "colProductName": "Mặt Hàng",
    "colQty": "SL",
    "colUnitPrice": "Đơn Giá",
    "colTax": "Thuế",
    "colLineTotal": "Thành Tiền",
    "editItemTooltip": "Sửa",
    "removeItemTooltip": "Xóa dòng",
    "subTotal": "Cộng tiền hàng",
    "totalTax": "Tiền thuế",
    "grandTotal": "Tổng Hóa Đơn",
    "cancelBtn": "Hủy",
    "savingBtn": "Đang lưu...",
    "saveBtn": "Lưu Hóa Đơn"
};

dict.purchaseBills = { ...newKeys, ...(dict.purchaseBills || {}) };
fs.writeFileSync(dictPath, JSON.stringify(dict, null, 4));
console.log("Successfully updated vi.json");
